using System.Security.Cryptography;
using System.Text;
using IntegratedContro.Core;

namespace IntegratedContro.Infrastructure;

public sealed record ManagedMediaSetup(int Version, int ApiPort, int HlsPort, int RtspPort, Guid CredentialId)
{
    public int ConfigurationVersion { get; init; } = 1;
    [System.Text.Json.Serialization.JsonIgnore]
    public MediaConfiguration Configuration => new(ConfigurationVersion, $"http://127.0.0.1:{ApiPort}", $"http://127.0.0.1:{HlsPort}",
        "integrated-api", "integrated-hls", CredentialId);
}

public static class ManagedMediaConfiguration
{
    // MediaMTX 1.21 supports base64 SHA-256 credentials. Generated passwords have 256 bits of entropy.
    private static string Hash(string password) => "sha256:" + Convert.ToBase64String(SHA256.HashData(Encoding.UTF8.GetBytes(password)));
    public static string ConfigurationText(ManagedMediaSetup setup, MediaCredentials credentials) => $"""
        # Generated by IntegratedContro. Keep with the host data and protected credentials.
        logLevel: warn
        logDestinations: [stdout]
        api: yes
        apiAddress: 127.0.0.1:{setup.ApiPort}
        rtsp: yes
        rtspAddress: 127.0.0.1:{setup.RtspPort}
        rtspTransports: [tcp]
        rtmp: no
        webrtc: no
        srt: no
        moq: no
        hls: yes
        hlsAddress: 127.0.0.1:{setup.HlsPort}
        hlsVariant: mpegts
        hlsSegmentCount: 4
        hlsSegmentDuration: 1s
        hlsSegmentMaxSize: 32M
        hlsMuxerCloseAfter: 10s
        hlsDirectory: ''
        authMethod: internal
        authInternalUsers:
          - user: integrated-api
            pass: '{Hash(credentials.ApiPassword)}'
            ips: ['127.0.0.1']
            permissions:
              - action: api
          - user: integrated-hls
            pass: '{Hash(credentials.HlsPassword)}'
            ips: ['127.0.0.1']
            permissions:
              - action: read
                path: '~^ic-'
        """ + "\npaths: {}\n";
}
